In [4]:
import numpy as np

In [5]:
qtd = [1,2,3,4]
custo = [100,200,300,4000]

In [6]:
array1 = np.array(qtd)

In [7]:
array2 = np.array(custo)

In [8]:
estoque = array1 * array2

In [9]:
estoque

array([  100,   400,   900, 16000])

In [10]:
custo = [100, 200, 300, 400]
venda = [150, 300, 450, 600]
arr_custo = np.array(custo)
arr_venda = np.array(venda)

In [11]:
arr_lucro = arr_venda - arr_custo

In [12]:
arr_lucro

array([ 50, 100, 150, 200])

In [13]:
arr_porcentagem = (arr_venda/arr_custo - 1) * 100

In [14]:
print(f"{arr_porcentagem[0]}%")

50.0%


In [17]:
#array a partir do np: arrange()
x = int(input())
final = (x*10)+1
np.arange(0, final , x)

 5


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
#linspace
np.linspace(1,10,5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
#modulo random -> rand, randn e randint

In [20]:
np.random.rand(3)

array([0.36475959, 0.42210574, 0.21643601])

In [21]:
np.random.randint(1, 10, 20)

array([8, 9, 3, 3, 8, 6, 2, 6, 6, 3, 9, 1, 2, 1, 7, 3, 6, 9, 5, 8])

In [24]:
#matriz
np.zeros((3,3)) # ou np.ones pra 1 ou np.eye (matriz diagonal)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])