In [40]:
import numpy as np

In [41]:
qtd = [1,2,3,4]
custo = [100,200,300,4000]

In [42]:
array1 = np.array(qtd)

In [43]:
array2 = np.array(custo)

In [44]:
estoque = array1 * array2

In [45]:
estoque

array([  100,   400,   900, 16000])

In [46]:
custo = [100, 200, 300, 400]
venda = [150, 300, 450, 600]
arr_custo = np.array(custo)
arr_venda = np.array(venda)

In [47]:
arr_lucro = arr_venda - arr_custo

In [48]:
arr_lucro

array([ 50, 100, 150, 200])

In [49]:
arr_porcentagem = (arr_venda/arr_custo - 1) * 100

In [50]:
print(f"{arr_porcentagem[0]}%")

50.0%


In [52]:
#array a partir do np: arrange()
x = int(input())
final = (x*10)+1
np.arange(0, final , x)

 5


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [53]:
#linspace
np.linspace(1,10,5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [54]:
#modulo random -> rand, randn e randint

In [55]:
np.random.rand(3)

array([0.47060363, 0.42859221, 0.54532369])

In [56]:
np.random.randint(1, 10, 20)

array([9, 6, 6, 5, 2, 3, 9, 7, 5, 3, 7, 9, 6, 5, 4, 2, 3, 4, 5, 2])

In [57]:
#matriz
np.zeros((3,3)) # ou np.ones pra 1 ou np.eye (matriz diagonal)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
cadastro = np.random.randint(15, 51, size=(50,10))

In [59]:
cadastro_18 = cadastro > 18

In [60]:
cadastro_18

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True, False,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, 

In [61]:
array3 = cadastro[cadastro_18]

In [62]:
len(array3)

449

In [63]:
condicao = (cadastro > 30)

In [64]:
extraido = np.extract(condicao, cadastro)

In [65]:
extraido

array([39, 39, 40, 42, 47, 40, 46, 36, 39, 33, 34, 35, 49, 33, 35, 46, 31,
       47, 33, 50, 50, 33, 35, 33, 45, 33, 44, 45, 47, 39, 49, 35, 35, 50,
       37, 32, 40, 41, 48, 39, 44, 37, 50, 31, 32, 41, 31, 33, 43, 37, 36,
       49, 37, 38, 45, 48, 34, 42, 39, 40, 46, 35, 43, 41, 46, 46, 37, 39,
       45, 47, 48, 31, 37, 31, 31, 42, 46, 32, 43, 45, 49, 32, 31, 34, 34,
       40, 40, 32, 50, 36, 39, 49, 40, 44, 43, 38, 50, 46, 35, 31, 46, 47,
       37, 37, 33, 39, 34, 46, 36, 38, 31, 37, 37, 49, 31, 36, 48, 47, 38,
       40, 46, 35, 32, 47, 41, 48, 39, 49, 47, 47, 34, 40, 31, 36, 43, 38,
       50, 45, 39, 39, 44, 50, 37, 47, 44, 49, 32, 46, 40, 42, 36, 46, 31,
       34, 47, 46, 50, 50, 42, 46, 48, 50, 36, 36, 50, 44, 46, 38, 31, 47,
       39, 42, 37, 38, 50, 35, 33, 45, 43, 43, 47, 41, 36, 31, 46, 42, 40,
       43, 45, 46, 39, 46, 46, 33, 43, 39, 38, 50, 46, 49, 37, 43, 40, 31,
       39, 39, 42, 47, 38, 46, 31, 32, 47, 38, 33, 40, 47, 38, 40, 32, 36,
       32, 43, 46, 33, 47